data:
  use_case: mnist # mnist, cifar-10
  save_data:
    set_save_path: False
    path: '/Users/Donovan/Documents/Masters/masters-ed02/coding/model_cnn_ga_3/'

  X_path: '/Users/Donovan/Documents/Masters/masters-ed02/coding/model_base_cnn/train/X.npy'
  Y_path: '/Users/Donovan/Documents/Masters/masters-ed02/coding/model_base_cnn/train/Y.npy'
  data_sample_size: 1000 # Integer or None

  # Only applies to gibbon
  replace: True
  test_set_size: 0.4
  test_val_split: 0.5

general:
  seed_value: 42 # Integer or None
  verbose: 2
  epochs: 10

model:
  convolution:
    kernel: [1, 3]
    filter: [2, 4, 8, 16, 32, 64, 128, 256]
    padding: ['same']

  pooling:
    type: ['max', 'average']
    size: [2, 3, 4, 5]
    padding: ['same']

  dropout:
    rate: [0.0, 0.7]

neat:
  block:
    population_size: 2
    node_mutation_probability: 0.1